### ISSUE TITLE
What is AdbcStatementInit supposed to do

### ISSUE THREAD

**Issue by hannes** [lidavidm/arrow#10]
This seems like its not required, since all the methods that do something with statements (e.g. SqlExecute) also get the connection and can just create statements.

**Comment by hannes** [comment]
In a similar vein, do we still need to call StatementRelease if an error has occurred in SqlExecute etc?

**Comment by hannes** [comment]
To address this, we could also remove the connection parameter from SqlExecute

**Comment by lidavidm** [comment]
My thought was that if we wanted to set parameters that might affect SqlExecute and so on, we would have to init the statement first

**Comment by lidavidm** [comment]
I was thinking we should always require calling the *Release functions but that needs to be clarified

**Comment by lidavidm** [comment]
So related to #7 maybe the pattern we go with is always

```c
AdbcFoo foo; // e.g. database, connection, statement
AdbcFooNew(&foo);
AdbcFooSetOption(&foo, key, value);
AdbcFooExecute(&foo);
AdbcFooRelease(&foo); 
```

How does that sound? CC @krlmlr

And then we can reorganize things a bit for consistency, at maybe the cost of some boilerplate, e.g.

```c
AdbcStatement stmt;
AdbcStatementNew(&conn, &stmt);
AdbcStatementSetSqlQuery(&stmt, "SELECT 1"); // or use AdbcStatementSetSubstraitPlan(AdbcStatement*, const uint8_t*);
// We can also set other options, e.g. desired batch size, or custom type mappings, ...
AdbcStatementExecute(&stmt); // or AdbcStatementPrepare
// ... consume the result set ...
AdbcStatementRelease(&stmt);
```

**Comment by lidavidm** [comment]
See https://github.com/apache/arrow-adbc/pull/5 and https://github.com/apache/arrow-adbc/pull/6 which refactor error handling and initialization, respectively. In particular it follows a DuckDB-ish `AdbcFooSetOption` pattern now. Also the driver manager doesn't require a separate entrypoint anymore, you can:

```c
AdbcDatabaseNew(&database, &error);
AdbcDatabaseSetOption(&database, "driver", "libadbc_driver_sqlite.so", &error);
AdbcDatabaseSetOption(&database, "entrypoint", "AdbcSqliteDriverInit", &error);
AdbcDatabaseInit(&database, &error);
```
