### ISSUE TITLE
Query parameters and data ingestion

### ISSUE THREAD

**Issue by krlmlr** [lidavidm/arrow#5]
Are we going to support query parameters?

How should the support for data ingestion look like?

Both issues might be a bit similar. In DBI we have support for sending multiple sets of parameters for the same prepared query in one call. Data ingestion should accept Arrow C Data, maybe we could solve parameters the same way?

CC @hannes @nbenn.

**Comment by lidavidm** [comment]
Agreed that query parameters probably look like data ingestion and should just let you specify a table of values.

Looking at https://dbi.r-dbi.org/reference/dbbind I see
> vectors of arbitrary length (including length 0) are supported. For queries, calling [dbFetch()](https://dbi.r-dbi.org/reference/dbfetch) binding such parameters returns concatenated results, equivalent to binding and fetching for each set of values and connecting via [rbind()](https://rdrr.io/r/base/cbind.html)
Is it ever useful to return multiple result sets instead?

**Comment by krlmlr** [comment]
I felt bound by the original interface in DBI, for a new version we can certainly do things differently -- also return multiple result sets or data streams.

**Comment by lidavidm** [comment]
Thanks. I guess we could do both if needed. 

Latest commit starts sketching out prepared statements, albeit without parameters implemented, and then we need to sketch out ingestion.

**Comment by lidavidm** [comment]
Prepared statements with parameters added (clumsily) for SQLite (but not Flight SQL) in the latest update. I'll probably go refactor things as described in #10 next.

**Comment by lidavidm** [comment]
Bulk ingestion: https://github.com/apache/arrow-adbc/commit/612bb9dcca1561ebfe27453ed9e24f8b524253f5
