### ISSUE TITLE
null-terminated strings

### ISSUE THREAD

**Issue by hannes** [lidavidm/arrow#6]
the ODBC string length thing is pretty annoying, and most of the time its null-terminated anyway. can we not make this the convention, e.g. string parameters need to be null-terminated?

**Comment by hannes** [comment]
Also, `const char **table_types` in `AdbcConnectionGetTables` does not have individual lengths, either ^^

**Comment by hannes** [comment]
Maybe it would be nicer to have a struct parameter to GetTables

**Comment by lidavidm** [comment]
Updated to drop the string lengths everywhere. 

GetTables could warrant a struct, yes. Also table_types should probably specify how to terminate the array
