### ISSUE TITLE
Connection Strings

### ISSUE THREAD

**Issue by hannes** [lidavidm/arrow#7]
Driver manager and connection use `key=value;` pairs to set critical config. Maybe a different structure would be preferable, e.g. we use arbitrary key/value strings in the form of a parameter map in DuckDB. Would simplify parsing...

**Comment by lidavidm** [comment]
Changed in https://github.com/apache/arrow-adbc/commit/a9f3e78eac0d56a991dc19fd23c4b6b88419ea97 to mimic the DuckDB initialization more.
